autoconf; check for bc and sshpass

diff --git a/plugins/router/mikrotik_system b/plugins/router/mikrotik_system
--- a/plugins/router/mikrotik_system
+++ b/plugins/router/mikrotik_system
@@ -369,8 +369,14 @@ get_cpu_count
 # munin-Logik
 # wenn $1 = X; dann
 if [ "$1" = "autoconf" ]; then
-  echo yes
-  exit 0
+    if ! command -v bc &> /dev/null; then
+        echo "[ERROR] bc could not be found!"
+    elif ! command -v sshpass &> /dev/null; then
+        echo "[ERROR] sshpass could not be found!"
+    else
+        echo "yes"
+    fi
+    exit 0
 fi
 if [ "$1" = "config" ]; then
   # gebe label aus
