cake: error message fix

diff --git a/plugins/cake/cake_tin_throughput_ b/plugins/cake/cake_tin_throughput_
--- a/plugins/cake/cake_tin_throughput_
+++ b/plugins/cake/cake_tin_throughput_
@@ -129,7 +129,7 @@ if [ $has_if_in -eq 0 ]; then
 	diffserv_in_no="$(tc_cake_get_diffserv "$DEVICE_IN")"
 	
 	if [ ! "$diffserv_no" == "$diffserv_in_no" ]; then
-		echo "cake_tin_delay_: diffserv setting different between egress and ingress device - this cannot be plotted, exiting" >&2
+		echo "cake_tin_throughput_: diffserv setting different between egress and ingress device - this cannot be plotted, exiting" >&2
 		exit 1
 	fi
 fi
