check with autoconf

diff --git a/plugins/proxmox/proxmox_vm_count b/plugins/proxmox/proxmox_vm_count
--- a/plugins/proxmox/proxmox_vm_count
+++ b/plugins/proxmox/proxmox_vm_count
@@ -4,18 +4,22 @@
 : << EOF
 =head1 NAME
 proxmox_vm_count - Outputs the running, stopped and total counts of ProxMox VMs and LXCs.
+
 =head1 CONFIGURATION
 This plugin needs to run as the root user in order to have permission to run lvs and vgs
   [proxmox_vm_count]
   [proxmox_count]
   user root
   group root
+
 =head1 AUTHOR
 =over 4
 =item * Michael Grote
 =back
+
 =head1 LICENSE
 Unknown license
+
 =head1 MAGIC MARKERS
 =begin comment
 These magic markers are used by munin-node-configure when installing
@@ -24,17 +28,19 @@ munin-node.
   #%# family=auto
   #%# capabilities=autoconf suggest
 =cut
+
 EOF
 
-if ! command -v qm &> /dev/null
-then
-    echo "[ERROR] qm could not be found!"
-    exit 1
-fi
-if ! command -v pct &> /dev/null
-then
-    echo "[ERROR] pct could not be found!"
-    exit 1
+
+if [ "$1" = "autoconf" ]; then
+    if ! command -v qm &> /dev/null; then
+        echo "[ERROR] qm could not be found!"
+    elif ! command -v pct &> /dev/null, then
+        echo "[ERROR] pct could not be found!"
+    else
+        echo "yes"
+    fi
+    exit 0
 fi
 
 # hole Variablen nur einmal
