Error Messages

diff --git a/plugins/proxmox/proxmox_count b/plugins/proxmox/proxmox_count
--- a/plugins/proxmox/proxmox_count
+++ b/plugins/proxmox/proxmox_count
@@ -12,11 +12,13 @@
 
 if ! command -v qm &> /dev/null
 then
-    exit
+    echo "[ERROR] qm could not be found!"
+    exit 1
 fi
 if ! command -v pct &> /dev/null
 then
-    exit
+    echo "[ERROR] pct could not be found!"
+    exit 1
 fi
 
 # hole Variablen nur einmal
