Make whitespace consistent, converting tabs to 4 spaces and fixing indents

diff --git a/plugins/network/mtr100_ b/plugins/network/mtr100_
--- a/plugins/network/mtr100_
+++ b/plugins/network/mtr100_
@@ -21,8 +21,8 @@
 #
 # Parameters:
 #
-# 	config   (required)
-# 	autoconf (optional - only used by munin-config)
+#     config   (required)
+#     autoconf (optional - only used by munin-config)
 #
 # Magic markers (optional - used by munin-config and some installation
 # scripts):
@@ -32,19 +32,19 @@
 totrace=`basename $0 | sed 's/^mtr100_//g'`
 
 if [ "$1" = "autoconf" ]; then
-	if ( mtr -nrc 1 localhost 2>/dev/null >/dev/null ); then
-		echo yes
-		exit 0
-	else
-		if [ $? -eq 127 ]
-		then
-			echo "no (mtr program not found - install the mtr(-tiny) package)"
-			exit 1
-		else
-			echo no
-			exit 1
-		fi
-	fi
+    if ( mtr -nrc 1 localhost 2>/dev/null >/dev/null ); then
+        echo yes
+        exit 0
+    else
+        if [ $? -eq 127 ]
+        then
+            echo "no (mtr program not found - install the mtr(-tiny) package)"
+            exit 1
+        else
+            echo no
+            exit 1
+        fi
+    fi
 exit 0
 fi
 
@@ -63,28 +63,28 @@ total+=$6
 }
 
 END {
-	if ( C != "config" ) { print "hop_0.value U" }
-	if ( C == "config" ) { print "hop_0.label " SRC_HOSTNAME }
-	if ( C == "config" ) { print "hop_0.draw AREA" }
-	for (x=1; x<=count; x++) {
-		value=(val[x]/total)*100
-		if ( C != "config" ) { printf "%s.value %2.2f\n","hop_" lab[x],value }
-		if ( C == "config" ) { print "hop_" lab[x] ".label " name[x] }
-		if ( C == "config" ) { print "hop_" lab[x]".draw STACK" }
-        }
+    if ( C != "config" ) { print "hop_0.value U" }
+    if ( C == "config" ) { print "hop_0.label " SRC_HOSTNAME }
+    if ( C == "config" ) { print "hop_0.draw AREA" }
+    for (x=1; x<=count; x++) {
+        value=(val[x]/total)*100
+        if ( C != "config" ) { printf "%s.value %2.2f\n","hop_" lab[x],value }
+        if ( C == "config" ) { print "hop_" lab[x] ".label " name[x] }
+        if ( C == "config" ) { print "hop_" lab[x]".draw STACK" }
+    }
 }'
 }
 
 if [ "$1" = "config" ]; then
-        echo 'graph_title Traceroute (%) to '$totrace
-        echo 'graph_args --base 1000 -l 0 -u 100 -r'
-        echo 'graph_vlabel ms (percentage)'
-        echo 'graph_category network'
-	echo 'graph_scale no'
-        echo 'graph_period second'
-        echo 'graph_info This graph shows the Percentage needed for each hop on the way to '$totrace
-        dotrace config;
-        exit 0
+    echo 'graph_title Traceroute (%) to '$totrace
+    echo 'graph_args --base 1000 -l 0 -u 100 -r'
+    echo 'graph_vlabel ms (percentage)'
+    echo 'graph_category network'
+    echo 'graph_scale no'
+    echo 'graph_period second'
+    echo 'graph_info This graph shows the Percentage needed for each hop on the way to '$totrace
+    dotrace config;
+    exit 0
 else
-	dotrace;
+    dotrace;
 fi
