autoconf added + check availability zpool

diff --git a/plugins/zfs/zpool_fragmentation b/plugins/zfs/zpool_fragmentation
--- a/plugins/zfs/zpool_fragmentation
+++ b/plugins/zfs/zpool_fragmentation
@@ -25,15 +25,19 @@ munin-node.
 
 EOF
 
+if [ "$1" = "autoconf" ]; then
+    if ! command -v zpool &> /dev/null; then
+        echo "[ERROR] zpool could not be found!"
+    else
+        echo "yes"
+    fi
+    exit 0
+fi
+
 # lese alle pools, sed löscht die erste zeile
 # entferne das %-zeichen
 list=$(zpool list | sed 1d | tr -d %)
 
-# wenn parameter = ...
-if [ "$1" = "autoconf" ]; then
-  echo yes
-  exit 0
-fi
 
 if [ "$1" = "config" ]; then
   # https://superuser.com/questions/284187/bash-iterating-over-lines-in-a-variable
