Handle missing rabbitmqctl

diff --git a/plugins/rabbitmq/rabbitmq_connections b/plugins/rabbitmq/rabbitmq_connections
--- a/plugins/rabbitmq/rabbitmq_connections
+++ b/plugins/rabbitmq/rabbitmq_connections
@@ -89,4 +89,11 @@ fi
 # real work - i.e. display the data. Almost always this will be
 # "value" subfield for every data field.
 
-echo "connections.value $(HOME=$HOME rabbitmqctl list_connections | grep -v "^Listing" | grep -v "done.$" | wc -l)"
+if hash rabbitmqctl >/dev/null 2>&1; then
+    connections=$(HOME=/tmp rabbitmqctl list_connections state | grep -c running)
+else
+    echo "$0: Could not run rabbitmqctl" >&2
+    connections=U
+fi
+
+printf "connections.value %s\n" "$connections"
