Check if we are running as a user required by rabbitmqctl

diff --git a/plugins/rabbitmq/rabbitmq_connections b/plugins/rabbitmq/rabbitmq_connections
--- a/plugins/rabbitmq/rabbitmq_connections
+++ b/plugins/rabbitmq/rabbitmq_connections
@@ -42,6 +42,16 @@ Optional, default value is 1000
 
 =cut
 
+case $(whoami) in
+    rabbitmq|root)
+        ;;
+    *)
+        echo 'Error: Plugin requires "user" to be set in plugin configuration.' >&2
+        echo 'See "munindoc rabbitmq_connections" for more information'  >&2
+        exit 1
+        ;;
+esac
+
 # If run with the "config"-parameter, give out information on how the
 # graphs should look. 
 
