[nextcloud_] Softer failure on missing data
Signed-off-by: Olivier Mehani <shtrom@ssji.net>

diff --git a/plugins/nextcloud/nextcloud_ b/plugins/nextcloud/nextcloud_
--- a/plugins/nextcloud/nextcloud_
+++ b/plugins/nextcloud/nextcloud_
@@ -70,10 +70,13 @@ PASSWORD="${password:-}"
 
 print_json_data() {
     local FIRST="$1"
-    [ -z "$FIRST" ] && (echo "incorrect call to print_json_data $*">&2; exit 1)
+    local VALUE="U"
     shift 1
+    test -z "$FIRST" && echo "missing data for 'print_json_data "" $*'">&2
     for KEY in "$@"; do
-        VALUE=$(echo "$FIRST" | jq -cr ".$KEY")
+        if [ -n "$FIRST" ]; then
+		VALUE=$(echo "$FIRST" | jq -cr ".$KEY")
+	fi
         echo "$KEY.value $VALUE"
    done
 }
