Rename plugin folder, check for json

diff --git a/plugins/jitsi/jitsi_videobridge b/plugins/jitsi/jitsi_videobridge
--- a/plugins/jitsi/jitsi_videobridge
+++ b/plugins/jitsi/jitsi_videobridge
@@ -50,7 +50,7 @@ case $1 in
     autoconf)
         if [ -x /usr/bin/curl ]; then
             if [ -x /usr/bin/jq ]; then
-	        curl -s -f -m 2 -I "$COLIBRI_URL" > /dev/null && echo "yes" && exit 0 || echo "no (no valid env.url)" && exit 0
+	        curl -s -f -m 2 -I "$COLIBRI_URL" | grep -iq "Content-Type: application/json" && echo "yes" && exit 0 || echo "no (invalid or empty response from colibri API ($COLIBRI_URL))" && exit 0
             else
                 echo "no (jq not found)" && exit 0
             fi
