unify error messages

diff --git a/plugins/http/http_response b/plugins/http/http_response
--- a/plugins/http/http_response
+++ b/plugins/http/http_response
@@ -206,7 +206,7 @@ check_programs_installed() {
 }
 
 if [[ "${BASH_VERSINFO:-0}" -lt 4 ]]; then
-    >&2 echo "The plugin http_response needs at least bash version 4"
+    >&2 echo "The plugin http_response needs at least bash version 4. Aborting."
     exit 1
 fi
 
@@ -218,7 +218,7 @@ short_label=${short_label:-"false"}
 follow_redirect=${follow_redirect:-"false"}
 
 if [[ ! "$max_time" =~ ^[0-9]+$ ]]; then
-    >&2 echo "Invalid configuration: max_time $max_time must contain only digits"
+    >&2 echo "Invalid configuration: max_time $max_time must contain only digits. Aborting."
     exit 1
 fi
 
