Added some basic checks to lvm_

diff --git a/plugins/disk/lvm_ b/plugins/disk/lvm_
--- a/plugins/disk/lvm_
+++ b/plugins/disk/lvm_
@@ -24,8 +24,14 @@
 #%# capabilities=autoconf suggest
 
 if [ "$1" = "autoconf" ]; then
-        echo yes
-        exit 0
+    if ! which lvs 2>/dev/null; then
+        echo "no (lvs not found)"
+    elif ! which vgs 2>/dev/null; then
+        echo "no (vgs not found)"
+    else
+        echo "yes"
+    fi
+    exit 0
 fi
 
 if [ "$1" = "suggest" ]; then
