[debsecan] More verbose errors
Signed-off-by: Olivier Mehani <shtrom@ssji.net>

diff --git a/plugins/system/debsecan b/plugins/system/debsecan
--- a/plugins/system/debsecan
+++ b/plugins/system/debsecan
@@ -37,13 +37,14 @@ if [ "$1" = "autoconf" ] ; then
   if [ -x /usr/bin/debsecan ]; then
     echo yes
   else
-    echo no
+    echo 'no (/usr/bin/debsecan not found)'
   fi
   exit 0
 fi
 
 # Fail if we don't have debsecan
 if [ ! -x /usr/bin/debsecan ]; then
+  echo 'error: /usr/bin/debsecan not found' >&2
   exit 1
 fi
 
